version: "3.7"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_MONGO_NAME}
      #MONGO_INITDB_ROOT_USERNAME: ${DATABASE_MONGO_USER}
      #MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_MONGO_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - ~/.opt/storage/rest_db:/data/db
    networks:
      - web

networks:
  web:
    external: true
  internal:
    external: false
